In [1]:
import numpy as np
import pandas as pd
import sys

In [4]:
# 读取数据
source_data = pd.read_csv("data/hw1_data/train.csv", encoding="big5")
source_data

,日期,測站,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014/1/1,豐原,AMB_TEMP,14,14,14,13,12,12,12,...,22,22,21,19,17,16,15,15,15,15
1,2014/1/1,豐原,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,2014/1/1,豐原,CO,0.51,0.41,0.39,0.37,0.35,0.3,0.37,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,2014/1/1,豐原,NMHC,0.2,0.15,0.13,0.12,0.11,0.06,0.1,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,2014/1/1,豐原,NO,0.9,0.6,0.5,1.7,1.8,1.5,1.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,2014/12/20,豐原,THC,1.8,1.8,1.8,1.8,1.8,1.7,1.7,...,1.8,1.8,2,2.1,2,1.9,1.9,1.9,2,2
4316,2014/12/20,豐原,WD_HR,46,13,61,44,55,68,66,...,59,308,327,21,100,109,108,114,108,109
4317,2014/12/20,豐原,WIND_DIREC,36,55,72,327,74,52,59,...,18,311,52,54,121,97,107,118,100,105
4318,2014/12/20,豐原,WIND_SPEED,1.9,2.4,1.9,2.8,2.3,1.9,2.1,...,2.3,2.6,1.3,1,1.5,1,1.7,1.5,2,2
4319,2014/12/20,豐原,WS_HR,0.7,0.8,1.8,1,1.9,1.7,2.1,...,1.3,1.7,0.7,0.4,1.1,1.4,1.3,1.6,1.8,2

In [5]:
# 只取数值部分
data = source_data.iloc[:11,3:]
data

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,14,14,14,13,12,12,12,12,15,17,...,22,22,21,19,17,16,15,15,15,15
1,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,0.51,0.41,0.39,0.37,0.35,0.3,0.37,0.47,0.78,0.74,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,0.2,0.15,0.13,0.12,0.11,0.06,0.1,0.13,0.26,0.23,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,0.9,0.6,0.5,1.7,1.8,1.5,1.9,2.2,6.6,7.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
5,16,9.2,8.2,6.9,6.8,3.8,6.9,7.8,15,21,...,11,11,22,28,19,12,8.1,7,6.9,6
6,17,9.8,8.7,8.6,8.5,5.3,8.8,9.9,22,29,...,14,13,25,30,21,13,9.7,8.6,8.7,7.5
7,16,30,27,23,24,28,24,22,21,29,...,65,64,51,34,33,34,37,38,38,36
8,56,50,48,35,25,12,4,2,11,38,...,52,51,66,85,85,63,46,36,42,42
9,26,39,36,35,31,28,25,20,19,30,...,36,45,42,49,45,44,41,30,24,13
10,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR

In [6]:
# 将 'RAINFALL' 行的 'NR' 替换成数值 '0'
data[data == "NR"] = 0
data

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,14,14,14,13,12,12,12,12,15,17,...,22,22,21,19,17,16,15,15,15,15
1,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,0.51,0.41,0.39,0.37,0.35,0.3,0.37,0.47,0.78,0.74,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,0.2,0.15,0.13,0.12,0.11,0.06,0.1,0.13,0.26,0.23,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,0.9,0.6,0.5,1.7,1.8,1.5,1.9,2.2,6.6,7.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
5,16,9.2,8.2,6.9,6.8,3.8,6.9,7.8,15,21,...,11,11,22,28,19,12,8.1,7,6.9,6
6,17,9.8,8.7,8.6,8.5,5.3,8.8,9.9,22,29,...,14,13,25,30,21,13,9.7,8.6,8.7,7.5
7,16,30,27,23,24,28,24,22,21,29,...,65,64,51,34,33,34,37,38,38,36
8,56,50,48,35,25,12,4,2,11,38,...,52,51,66,85,85,63,46,36,42,42
9,26,39,36,35,31,28,25,20,19,30,...,36,45,42,49,45,44,41,30,24,13
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# 将数据转化为 numpy 数组
raw_data = data.to_numpy()
raw_data

array([['14', '14', '14', '13', '12', '12', '12', '12', '15', '17', '20',
        '22', '22', '22', '22', '22', '21', '19', '17', '16', '15', '15',
        '15', '15'],
       ['1.8', '1.8', '1.8', '1.8', '1.8', '1.8', '1.8', '1.8', '1.8',
        '1.8', '1.8', '1.8', '1.8', '1.8', '1.8', '1.8', '1.8', '1.8',
        '1.8', '1.8', '1.8', '1.8', '1.8', '1.8'],
       ['0.51', '0.41', '0.39', '0.37', '0.35', '0.3', '0.37', '0.47',
        '0.78', '0.74', '0.59', '0.52', '0.41', '0.4', '0.37', '0.37',
        '0.47', '0.69', '0.56', '0.45', '0.38', '0.35', '0.36', '0.32'],
       ['0.2', '0.15', '0.13', '0.12', '0.11', '0.06', '0.1', '0.13',
        '0.26', '0.23', '0.2', '0.18', '0.12', '0.11', '0.1', '0.13',
        '0.14', '0.23', '0.18', '0.12', '0.1', '0.09', '0.1', '0.08'],
       ['0.9', '0.6', '0.5', '1.7', '1.8', '1.5', '1.9', '2.2', '6.6',
        '7.9', '4.2', '2.9', '3.4', '3', '2.5', '2.2', '2.5', '2.3',
        '2.1', '1.9', '1.5', '1.6', '1.8', '1.5'],
       ['16', '9.2', '8.2', '6.9', '6.8', '3.8', '6.9', '7.8', '15',
        '21', '14', '11', '14', '12', '11', '11', '22', '28', '19', '12',
        '8.1', '7', '6.9', '6'],
       ['17', '9.8', '8.7', '8.6', '8.5', '5.3', '8.8', '9.9', '22',
        '29', '18', '14', '17', '15', '14', '13', '25', '30', '21', '13',
        '9.7', '8.6', '8.7', '7.5'],
       ['16', '30', '27', '23', '24', '28', '24', '22', '21', '29', '44',
        '58', '50', '57', '65', '64', '51', '34', '33', '34', '37', '38',
        '38', '36'],
       ['56', '50', '48', '35', '25', '12', '4', '2', '11', '38', '56',
        '64', '56', '57', '52', '51', '66', '85', '85', '63', '46', '36',
        '42', '42'],
       ['26', '39', '36', '35', '31', '28', '25', '20', '19', '30', '41',
        '44', '33', '37', '36', '45', '42', '49', '45', '44', '41', '30',
        '24', '13'],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]], dtype=object)